config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "chatroom#index"
  #get 'login', to: 'sessions#new'
  resources :users, only: [:index]
  resources :chatroom
  mount ActionCable.server, at: '/cable'

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true, length: {minimum: 1, maximum: 1000}
end

app/models/user.rb
#require 'enumerize'

class User < ApplicationRecord
  extend Enumerize
  enumerize :role, in: [:user, :admin], default: :user
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  validates :username, uniqueness: {case_sensitive: false},   
  presence: true, length: { minimum: 3, maximum: 25}

  validates :email, presence: true, length: { maximum: 105 }, 
  uniqueness: {case_sensitive: false}, format: {with: URI::MailTo::EMAIL_REGEXP, message: "invalid email format"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
  
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController 
    before_action :authenticate_user!, only: [:new]
    def index
        @messages = Message.all
        @new_message = Message.new

    end 

    def new 
    end 

    #def create 
    #    @message = Message.new(message_params)
    #    @message.user_id = current_user.id
    #    if @message.save
#
    #        ActionCable.server.broadcast "ChatroomChannel", foo: @message.body
    #    end 
    #end 
#
    def create
        @message = current_user.messages.build(message_params)  # This uses association build method
      
        if @message.save
          ActionCable.server.broadcast('ChatroomChannel',{ mod_message: message_render(@message)})
          #render json: { status: 'success', message: 'Message sent!' }, status: :ok
        else
          render json: @message.errors, status: :unprocessable_entity
        end
      end
      

    def destroy
        @message = Message.find(params[:id])
        @message.destroy
        redirect_to root_path
    end





    private

    def message_render(message)
        render(partial: 'messages/message', locals: { message: message})
    end
    def message_params
        params.require(:message).permit(:body)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/create.js.erb
<% if flash[:error] %>
<% true %>
<% else %>
document.getElementById('new-messages').innerHTML += "<%= j render @message %>";
  document.getElementById('new_message_form').reset();

<% end %>

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="blue chat icon"></i>
  ChatNet
</h4>

<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui fluid raised card chatbox">
      <div class="messages-overflow" id="new-messages">
        <div class="content">
          <div class="ui feed">
            <% @messages.each do |message| %>
            <%= render 'messages/message', message: message %>

              <% end %>
          </div>
        </div>
      </div>
      <div class="extra content">
        <% if !user_signed_in? %>
          Connectez vous pour envoyer un message.
          <% else %>
          <%= form_with(model: @new_message, local: false, url: chatroom_index_path, class: 'ui form', id: 'new_message_form') do |f| %>
          <div class="ui action input">
            <%= f.text_field :body, placeholder: "Type your message here...", class: 'ui input' %>
            <%= f.submit 'Send', class: 'ui button' %>
          </div>
        <% end %>
        
                <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<% if name.to_s == 'notice' %>
<div class="alert alert-success" role="alert">
   <%= msg %>
   </div>
  <% elsif name.to_s == 'alert' %>
  <div class="alert alert-danger" role="alert">
    <%= msg %>
  </div>
  <% end %>

  <% end %>

app/views/layouts/_navigation.html.erb
<a href='/' class="item">
  Chatroom
</a>
<a class="item">
  Stock
</a>
<div class="right menu">
<% if user_signed_in? %>
  <%=  link_to 'Logout', destroy_user_session_path, method: :delete, class:'item' %>

<% else %>
  <%=  link_to 'Sign in', new_user_session_path,  class:'item' %>

  </div>
  <div class="item">
      <div class="ui button"><%=  link_to 'Sign up', new_user_registration_path %>
</div>
  </div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= favicon_link_tag image_path('icon.png') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
          <%= render "layouts/messages" %>

      </div>
    </div>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary flex-container">
      <span class="message-content">
        <a><%= message.user.username %></a> : <%= message.body %>
      </span>
      <% if user_signed_in? && current_user == message.user %>
        <%= link_to chatroom_path(message), method: :delete, data: { confirm: 'Are you sure?' }, class: 'ui icon button extra-mini delete-button' do %>
          <i class="trash alternate outline icon"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>